[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "iporter"
version = "0.1"
description = "Local DNS server with source-IP group based rewrite rules"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Simon Nandor", email = "simonszoft@gmail.com" }]
dependencies = [
  "dnslib>=0.9.24",
  "Flask>=3.0.0",
  "PyYAML>=6.0.1",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.2.0",
]

[project.scripts]
iporter = "iporter.cli:main"
iporter-config-ui = "iporter.web_ui:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
