listen_host: 0.0.0.0
listen_port: 53
response_ttl: 60
policy_db_path: policy.db
local_lan_name: TESTER
support_user_email: support@localhost
support_user_name: Support
web_gui:
  host: 0.0.0.0
  port: 8080
upstream_dns_servers:
- host: 1.1.1.1
  port: 53
- host: 8.8.8.8
  port: 53
- host: 9.9.9.9
  port: 53
verbose_logging: true
log_file_path: iporter.log  